### ISSUE TITLE
Inquiry About Access to NAFLD-Anomaly and Liver-NAS Datasets

### ISSUE THREAD

**Issue by Huang-3** [7LFB/QAP#1]
Dear author,

I recently read your paper and found your work very interesting. I am particularly interested in using the NAFLD-Anomaly and Liver-NAS datasets for my research. Could you please let me know how I can access these datasets? A download link would be greatly appreciated.

Thank you for your time and assistance.

**Comment by 7LFB** [comment]
@Huang-3 
Thanks for your interest in the work. 
For NAFLD-Anomrly: [https://osf.io/gqutd/](url)
For Liver-NAS, it's a private dataset which is not publicly available yet.

**Comment by Huang-3** [comment]
> @Huang-3 Thanks for your interest in the work. For NAFLD-Anomrly: [https://osf.io/gqutd/](url) For Liver-NAS, it's a private dataset which is not publicly available yet.

Thank you for your help!
